# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_src_path: /Users/dreds/Documents/projects/algokit/templates/algokit-templates/templates/base-templates/algokit-typescript-template
author_email: ''
author_name: ''
contract_name: mycontract
preset_name: starter
project_name: typescript-template

