# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_src_path: /Users/dreds/Documents/projects/algokit/templates/algokit-templates/templates/base/frontend/react-vite
author_email: ''
author_name: ''
preset_name: starter
project_name: python-fullstack

