repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        description: "Run 'ruff format' for extremely fast Python formatting"
        entry: uv run ruff format
        language: system
        types: [python]
        args: [--no-cache]
        require_serial: true
        files: "^scripts/"
      - id: ruff
        name: ruff
        description: "Run 'ruff' for extremely fast Python linting"
        entry: uv run ruff check
        language: system
        "types": [python]
        args: [--fix, --no-cache]
        require_serial: false
        files: "^scripts/"
      - id: mypy
        name: mypy
        description: "`mypy` will check Python types for correctness"
        entry: uv run mypy
        language: system
        types_or: [python, pyi]
        require_serial: true
        files: "^scripts/"
      - id: examples-test
        name: examples-test
        description: "Create and test all examples"
        entry: bash -c 'make create-examples && make test-examples'
        language: system
        pass_filenames: false
        files: "^(templates/|generators/|scripts/|examples\\.yml)"
