[project]
name = "algokit-templates"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "copier>=9.5.0",
    "fire>=0.7.0",
    "pydantic>=2.10.6",
    "pyyaml>=6.0.2",
    "tomli>=2.2.1",
    "tomli-w>=1.2.0",
]
