name: Check Python Scripts

on:
  workflow_call:

jobs:
  check-python:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync

      - name: Check formatting with Ruff
        run: |
          # stop the build if there are files that don't meet formatting requirements
          uv run ruff format --check scripts/

      - name: Check linting with Ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          uv run ruff check scripts/

      - name: Check types with mypy
        run: uv run mypy scripts/
