name: On Main Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Permissions needed for example branches and calling other workflows
permissions:
  contents: read

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  create-example-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Generate bot token
        uses: actions/create-github-app-token@v1
        id: app_token
        with:
          app-id: ${{ secrets.BOT_ID }}
          private-key: ${{ secrets.BOT_SK }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app_token.outputs.token }}

      - name: Create Example Branches
        uses: ./.github/actions/create-example-branches
        with:
          github_token: ${{ steps.app_token.outputs.token }}

  # Call release workflow for beta releases
  create-beta-release:
    uses: ./.github/workflows/release.yml
    with:
      stable: 'false'
    secrets: inherit

  publish-demo-sites:
    runs-on: ubuntu-latest
    needs: create-example-branches
    steps:
      - name: Generate bot token
        uses: actions/create-github-app-token@v1
        id: app_token
        with:
          app-id: ${{ secrets.BOT_ID }}
          private-key: ${{ secrets.BOT_SK }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app_token.outputs.token }}

      - name: Build Demo Sites
        uses: ./.github/actions/build-demo-sites

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ steps.app_token.outputs.token }}
