name: On Pull Request (Codebase validation)

on:
  pull_request:
    paths-ignore:
      - "README.md"

  schedule:
    - cron: "0 8 * * 1" # Each monday 8 AM UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pr-check:
    name: Check Python
    uses: ./.github/workflows/check-scripts.yml

  examples-test:
    name: Test Examples
    needs: pr-check
    uses: ./.github/workflows/test-examples.yml
