name: Check Python Scripts

on:
  workflow_call:

jobs:
  check-python:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync

      - name: Install algokit
        run: uv tool install algokit

      - name: Install poetry (used in examples)
        run: uv tool install poetry

      - name: Validate example configuration
        run: make validate-example-configuration

      - name: Create examples
        run: make create-examples

      - name: Test examples
        run: make test-examples

      - name: Check output stability
        shell: bash
        run: |
          # Add untracked files as empty so they come up in diff
          git add -N ./examples
          # Look for changes in generated templates and error if there are any
          git diff --exit-code --minimal ./examples
